# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-16 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='artists',
            field=models.ManyToManyField(to='api.Music'),
        ),
        migrations.AlterField(
            model_name='album',
            name='aartist',
            field=models.ManyToManyField(blank=True, to='api.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(blank=True, to='api.Album'),
        ),
    ]
